workflows: add ccache option , disable wechat notification , disable repo url option

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -4,25 +4,14 @@ on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
-      repo_url:
-        description: 'openwrt repo url'
-        required: true
-        default: 'https://github.com/coolsnowwolf/lede'
-      repo_branch:
-        description: 'openwrt repo branch'
-        required: true
-        default: 'master'
-      config_url:
-        description: 'config repo url'
-        required: true
-        default: 'https://github.com/EnnawYang/openwrt-config'
-      config_branch:
-        description: 'config repo branch'
-        required: true
-        default: 'lean-lede'
       toolchain:
         description: 'skip compile toolchain [true/false]'
+        required: false
         default: 'true'
+      ccache:
+        description: 'apply ccache'
+        required: false
+        default: 'false'
       tar:
         description: 'upload openwrt .tar to GoogleDrive [true/false]'
         required: false
@@ -37,11 +26,11 @@ on:
         default: 'update'
 
 env:
-  REPO_URL: ${{ github.event.inputs.repo_url }}
-  REPO_BRANCH: ${{ github.event.inputs.repo_branch }}
+  REPO_URL: https://github.com/coolsnowwolf/lede
+  REPO_BRANCH: master
   REPO_FLODER: openwrt
-  CONFIG_REPO: ${{ github.event.inputs.config_url }}
-  CONFIG_BRANCH: ${{ github.event.inputs.config_branch }}
+  CONFIG_REPO: https://github.com/EnnawYang/openwrt-config
+  CONFIG_BRANCH: lean-lede
   CONFIG_FLODER: config-repo
   UPLOAD_BIN_DIR: true
   UPLOAD_FIRMWARE: true
@@ -82,6 +71,7 @@ jobs:
         sudo dpkg-reconfigure -f noninteractive tzdata
         echo "TARGET_NAME=${{ matrix.targets }}" >> $GITHUB_ENV
         echo "SKIP_TOOLCHAIN=${{ github.event.inputs.toolchain }}" >> $GITHUB_ENV
+        echo "CCACHE=${{ github.event.inputs.ccache }}"
         echo "TAR=${{ github.event.inputs.tar }}" >> $GITHUB_ENV
         echo "FILE_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
 
@@ -138,7 +128,8 @@ jobs:
         [ -e $GITHUB_WORKSPACE/$REPO_FLODER/.config ] && rm $GITHUB_WORKSPACE/$REPO_FLODER/.config*
         cp $GITHUB_WORKSPACE/$CONFIG_FLODER/"$TARGET_NAME".config $GITHUB_WORKSPACE/$REPO_FLODER/.config || exit 1
         sed -i '/CONFIG_DEVEL/d;/CONFIG_CCACHE/d;/CONFIG_BUILD_LOG/d' .config
-        echo -e "\nCONFIG_DEVEL=y\nCONFIG_CCACHE=y\nCONFIG_BUILD_LOG=y\nCONFIG_BUILD_LOG_DIR=\"./logs\"" >> .config
+        echo -e "\nCONFIG_DEVEL=y\nCONFIG_BUILD_LOG=y\nCONFIG_BUILD_LOG_DIR=\"./logs\"" >> .config
+        [[ $CCACHE == true ]] && echo -e "\nCONFIG_CCACHE=y" >> .config
         make defconfig
 
     - name: Download package
@@ -253,4 +244,4 @@ jobs:
       if: steps.compile.conclusion == 'success' && env.Notification == 'true' && !cancelled()
       run: |
         curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TG_CHAT_ID }} -d text=""$TARGET_NAME" compile succeeded" 2>&1 >/dev/null || echo "Telegram notification failed"
-        curl -s -X POST https://sctapi.ftqq.com/${{ secrets.SCTKEY }}.send?title=""$TARGET_NAME" compile succeeded" 2>&1 >/dev/null || echo "Wechat notification failed"
+        # curl -s -X POST https://sctapi.ftqq.com/${{ secrets.SCTKEY }}.send?title=""$TARGET_NAME" compile succeeded" 2>&1 >/dev/null || echo "Wechat notification failed"
