workflows: add ccache option , disable wechat notification

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -28,6 +28,10 @@ on:
         description: 'skip compile toolchain [true/false]'
         required: false
         default: 'true'
+      ccache:
+        description: 'apply ccache'
+        required: false
+        default: 'false'
       tar:
         description: 'upload openwrt .tar to GoogleDrive [true/false]'
         required: false
@@ -82,6 +86,7 @@ jobs:
         sudo dpkg-reconfigure -f noninteractive tzdata
         echo "TARGET_NAME=${{ github.event.inputs.name }}" >> $GITHUB_ENV
         echo "SKIP_TOOLCHAIN=${{ github.event.inputs.toolchain }}" >> $GITHUB_ENV
+        echo "CCACHE=${{ github.event.inputs.ccache }}"
         echo "TAR=${{ github.event.inputs.tar }}" >> $GITHUB_ENV
 
     - name: Checkout
@@ -137,7 +142,8 @@ jobs:
         [ -e $GITHUB_WORKSPACE/$REPO_FLODER/.config ] && rm $GITHUB_WORKSPACE/$REPO_FLODER/.config*
         cp $GITHUB_WORKSPACE/$CONFIG_FLODER/"$TARGET_NAME".config $GITHUB_WORKSPACE/$REPO_FLODER/.config || exit 1
         sed -i '/CONFIG_DEVEL/d;/CONFIG_CCACHE/d;/CONFIG_BUILD_LOG/d' .config
-        echo -e "\nCONFIG_DEVEL=y\nCONFIG_CCACHE=y\nCONFIG_BUILD_LOG=y\nCONFIG_BUILD_LOG_DIR=\"./logs\"" >> .config
+        echo -e "\nCONFIG_DEVEL=y\nCONFIG_BUILD_LOG=y\nCONFIG_BUILD_LOG_DIR=\"./logs\"" >> .config
+        [[ $CCACHE == true ]] && echo -e "\nCONFIG_CCACHE=y" >> .config
         make defconfig
 
     - name: Download package
@@ -224,6 +230,7 @@ jobs:
         cd $GITHUB_WORKSPACE/$REPO_FLODER
         make clean
         rm -rf dl files logs tmp package/diy
+        [[ $CCACHE == false ]] && rm -rf .ccache
         git reset --hard
         echo "tar openwrt floder"
         cd $GITHUB_WORKSPACE
@@ -252,4 +259,4 @@ jobs:
       if: steps.compile.conclusion == 'success' && env.Notification == 'true' && !cancelled()
       run: |
         curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TG_CHAT_ID }} -d text=""$TARGET_NAME" compile succeeded" 2>&1 >/dev/null || echo "Telegram notification failed"
-        curl -s -X POST https://sctapi.ftqq.com/${{ secrets.SCTKEY }}.send?title=""$TARGET_NAME" compile succeeded" 2>&1 >/dev/null || echo "Wechat notification failed"
+        # curl -s -X POST https://sctapi.ftqq.com/${{ secrets.SCTKEY }}.send?title=""$TARGET_NAME" compile succeeded" 2>&1 >/dev/null || echo "Wechat notification failed"
