scrpt: move to workflows

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -58,7 +58,6 @@ jobs:
         sudo -E apt-get -qq autoremove --purge
         sudo -E apt-get -qq clean
         sudo timedatectl set-timezone "$TZ"
-        chmod +x $GITHUB_WORKSPACE/script/*.sh
         echo "TARGET_NAME=${{ github.event.inputs.name }}" >> $GITHUB_ENV
         echo "TOOLCHAIN=${{ github.event.inputs.toolchain }}" >> $GITHUB_ENV
         echo "RM_DL=${{ github.event.inputs.rm_dl }}" >> $GITHUB_ENV
@@ -90,15 +89,69 @@ jobs:
       if: steps.install_rclone.conclusion == 'success' && !cancelled()
       run: |
         cd $GITHUB_WORKSPACE
-        bash script/download-openwrt.sh
+        (rclone copy $RCLONE_NAME:openwrt/repack/$TARGET_NAME-openwrt.tar . --transfers=8 -v && \
+        tar -xvf $TARGET_NAME-openwrt.tar 2>&1 >/dev/null && \
+        rm *-openwrt.tar && \
+        sudo chown -R $USER:$GROUPS $REPO_FLODER) || \
+        echo ">>>> skip download ..."
+
+    - name: Update source code
+      id: source
+      if: (!cancelled())
+      run: |
+        cd $GITHUB_WORKSPACE
+        git clone $CONFIG_REPO -b $CONFIG_BRANCH $CONFIG_FLODER --single-branch
+        ([ -d $GITHUB_WORKSPACE/$REPO_FLODER/.git ] && echo ">>>> update source code ...") || \
+        (echo ">>>> clone source code ..." && \
+        git clone $REPO_URL -b $REPO_BRANCH $REPO_FLODER --single-branch)
+        cd $GITHUB_WORKSPACE/$REPO_FLODER
+        ([ -d files ] && rm -rf files) || echo "files not found"
+        ([ -d logs ] && rm -rf logs) || echo "logs bot found"
+        ([ -d tmp ] && rm -rf tmp) || echo "tmp not found"
+        ([ -d package/diy ] && rm -rf package/diy) || echo "diy not found"
+        ([ -d dl/go-mod-cache ] && rm -rf dl/go-mod-cache) || echo "go-mod-cache not found"
+        git reset --hard
+        git pull && ./scripts/feeds update -a && ./scripts/feeds install -a
+
+    - name: Load custom configuration
+      id: custom
+      if: steps.source.conclusion == 'success' && !cancelled()
+      run: |
+        cd $GITHUB_WORKSPACE/$REPO_FLODER
+        chmod +x $GITHUB_WORKSPACE/$CONFIG_FLODER/*.sh
+        ([ -e $GITHUB_WORKSPACE/$CONFIG_FLODER/"$TARGET_NAME"-part2.sh ] && bash $GITHUB_WORKSPACE/$CONFIG_FLODER/"$TARGET_NAME"-part2.sh) || \
+        (bash $GITHUB_WORKSPACE/$CONFIG_FLODER/diy-part2.sh && echo -e ""$TARGET_NAME"-part2.sh not found, use diy-part2.sh")
+        [ -e $GITHUB_WORKSPACE/$REPO_FLODER/.config ] && rm $GITHUB_WORKSPACE/$REPO_FLODER/.config*
+        ([ -e $GITHUB_WORKSPACE/$CONFIG_FLODER/"$TARGET_NAME".config ] && cp $GITHUB_WORKSPACE/$CONFIG_FLODER/"$TARGET_NAME".config $GITHUB_WORKSPACE/$REPO_FLODER/.config) || \
+        (cp $GITHUB_WORKSPACE/$CONFIG_FLODER/.config $GITHUB_WORKSPACE/$REPO_FLODER/.config && echo -e ""$TARGET_NAME".config not found, use .config")
+        echo -e "\nCONFIG_DEVEL=y\nCONFIG_BUILD_LOG=y\nCONFIG_BUILD_LOG_DIR=\"./logs\"" >> .config
+        make defconfig
+
+    - name: Download package
+      id: package
+      if: steps.custom.conclusion == 'success' && !cancelled()
+      run: |
+        cd $GITHUB_WORKSPACE/$REPO_FLODER
+        [[ $RM_DL == true ]] && [ -d $GITHUB_WORKSPACE/$REPO_FLODER/dl ] && rm -rf $GITHUB_WORKSPACE/$REPO_FLODER/dl
+        make download -j16
+        find dl -size -1024c -exec ls -l {} \;
+        find dl -size -1024c -exec rm -f {} \;
 
     - name: Compile the firmware
       id: compile
       if: (!cancelled())
       run: |
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
-        cd $GITHUB_WORKSPACE
-        bash script/build-openwrt.sh
+        cd $GITHUB_WORKSPACE/$REPO_FLODER
+        echo -e ">>>> $(nproc) thread compile ..."
+        [[ $TOOLCHAIN == true ]] && make tools/compile -j$(nproc) && make toolchain/compile -j$(nproc)
+        make target/compile -j$(nproc) && \
+        make diffconfig && \
+        make package/compile -j$(nproc) && \
+        make package/index && \
+        make package/install -j$(nproc) && \
+        make target/install -j$(nproc) && \
+        make checksum
 
     - name: Check space usage
       if: (!cancelled())
@@ -192,7 +245,7 @@ jobs:
       uses: dev-drprasad/delete-older-releases@v0.2.0
       if: env.UPLOAD_RELEASE == 'true' && !cancelled()
       with:
-        keep_latest: 6
+        keep_latest: 5
         delete_tags: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -200,5 +253,5 @@ jobs:
     - name: Notification
       if: steps.compile.conclusion == 'success' && env.Notification == 'true' && !cancelled()
       run: |
-        curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TG_CHAT_ID }} -d text=""$TARGET_NAME"使用Actions编译完成"
-        curl https://sctapi.ftqq.com/${{ secrets.SCTKEY }}.send?title=""$TARGET_NAME"使用Actions编译完成"
+        curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TG_CHAT_ID }} -d text=""$TARGET_NAME" compile succeeded" 2>&1 >/dev/null || echo "Telegram notification failed"
+        curl -s -X POST https://sctapi.ftqq.com/${{ secrets.SCTKEY }}.send?title=""$TARGET_NAME" compile succeeded" 2>&1 >/dev/null || echo "Wechat notification failed"
