TEST2

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -4,14 +4,6 @@ on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
-      rm_dl:
-        description: 'delete dl floder [true/false]'
-        required: true
-        default: 'false'
-      tar:
-        description: 'upload openwrt .tar to GoogleDrive [true/false]'
-        required: true
-        default: 'true'
       release_note:
         description: 'release note'
         required: true
@@ -40,13 +32,66 @@ jobs:
       run: |
         sudo ln -fs /usr/share/zoneinfo/$TZ /etc/localtime
         sudo dpkg-reconfigure -f noninteractive tzdata
-        echo "TARGET_NAME=${{ github.job.container.id }}" >> $GITHUB_ENV
+
+    - name: Generate release tag
+      id: tag
+      if: (!cancelled())
+      run: |
+        echo "::set-output name=release_tag::TEST1"
+        touch release.txt
+        echo -e "${{ github.event.inputs.release_note }}" > release.txt
+        touch 1.txt
+        echo "1234567890" >1.txt
+
+    - name: Upload firmware to release
+      if: steps.tag.conclusion == 'success' && !cancelled()
+      uses: ncipollo/release-action@v1
+      with:
+        allowUpdates: true
+        token: ${{ secrets.GITHUB_TOKEN }}
+        tag: ${{ steps.tag.outputs.release_tag }}
+        bodyFile: release.txt
+        artifacts: 1.txt
+
+    - name: Notification
+      if: env.Notification == 'true' && !cancelled()
+      run: |
+        curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TG_CHAT_ID }} -d text=""$TARGET_NAME" TEST DONE." 2>&1 >/dev/null || echo "Telegram notification failed"
+
+
+  x86_64_1:
+    runs-on: ubuntu-20.04
+
+    steps:
+    - name: Initialization environment
+      env:
+        DEBIAN_FRONTEND: noninteractive
+      run: |
+        sudo ln -fs /usr/share/zoneinfo/$TZ /etc/localtime
+        sudo dpkg-reconfigure -f noninteractive tzdata
         echo "RM_DL=${{ github.event.inputs.rm_dl }}" >> $GITHUB_ENV
         echo "TAR=${{ github.event.inputs.tar }}" >> $GITHUB_ENV
 
-    - name: Echo env
+    - name: Generate release tag
+      id: tag
       if: (!cancelled())
-      run: echo -e "$TARGET_NAME"
+      run: |
+        echo "::set-output name=release_tag::TEST1"
+        touch release.txt
+        echo -e "${{ github.event.inputs.release_note }}" > release.txt
+        touch 2.txt
+        sleep 20
+        echo "0987654321" >2.txt
+
+    - name: Upload firmware to release
+      if: steps.tag.conclusion == 'success' && !cancelled()
+      uses: ncipollo/release-action@v1
+      with:
+        allowUpdates: true
+        token: ${{ secrets.GITHUB_TOKEN }}
+        tag: ${{ steps.tag.outputs.release_tag }}
+        bodyFile: release.txt
+        artifacts: 2.txt
 
     - name: Notification
       if: env.Notification == 'true' && !cancelled()
